import { describe, it, expect } from "vitest";
import {
  applyReflectionBlock,
  REFLECT_BLOCK_BEGIN,
  REFLECT_BLOCK_END,
} from "../src/commands/reflect.js";

const count = (haystack: string, needle: string): number =>
  haystack.split(needle).length - 1;

describe("applyReflectionBlock (I-008 — idempotent --apply)", () => {
  it("appends a sentinel-delimited block to fresh content", () => {
    const { content, replaced } = applyReflectionBlock("# CLAUDE.md\n", "Rule A");
    expect(replaced).toBe(false);
    expect(content).toContain(REFLECT_BLOCK_BEGIN);
    expect(content).toContain(REFLECT_BLOCK_END);
    expect(content).toContain("Rule A");
    expect(content).toContain("# CLAUDE.md");
  });

  it("replaces the existing block in place on re-apply (no duplicates)", () => {
    const first = applyReflectionBlock("# CLAUDE.md\n", "Rule A").content;
    const second = applyReflectionBlock(first, "Rule B");
    expect(second.replaced).toBe(true);
    expect(count(second.content, REFLECT_BLOCK_BEGIN)).toBe(1);
    expect(count(second.content, REFLECT_BLOCK_END)).toBe(1);
    expect(second.content).toContain("Rule B");
    expect(second.content).not.toContain("Rule A");
    // user content above the block is preserved
    expect(second.content).toContain("# CLAUDE.md");
  });

  it("is stable across many applies (exactly one block)", () => {
    let c = "# CLAUDE.md\n\nsome notes\n";
    for (let i = 0; i < 5; i++) c = applyReflectionBlock(c, `Rule ${i}`).content;
    expect(count(c, REFLECT_BLOCK_BEGIN)).toBe(1);
    expect(c).toContain("Rule 4");
    expect(c).toContain("some notes");
  });

  it("migrates a legacy (sentinel-less) auto-generated block", () => {
    const legacy =
      "# CLAUDE.md\n\nnotes\n\n---\n_Auto-generated by `ccmux reflect`_\n\nOld rule\n";
    const { content, replaced } = applyReflectionBlock(legacy, "New rule");
    expect(replaced).toBe(true);
    expect(count(content, REFLECT_BLOCK_BEGIN)).toBe(1);
    expect(content).toContain("New rule");
    expect(content).not.toContain("Old rule");
    expect(content).toContain("notes");
  });
});
