import chalk from "chalk";
import ora from "ora";
import fs from "fs/promises";
import path from "path";
import { spawn } from "child_process";
import { loadConfig } from "../config/schema.js";
import { resolveClaudeCmd } from "../integrations/autoclaw.js";

const CCMUX_DIR = process.env.CCMUX_DIR ?? `${process.env.HOME}/.ccmux`;

export interface ReflectOptions {
  apply?: boolean;
  backend?: "claude" | "autoclaw";
  outputFile?: string;
}

const REFLECTION_PROMPT = `You are a meta-learning agent analyzing a Claude Code session log.

Your task: identify patterns, mistakes, and improvements that should be captured as persistent rules.

Instructions:
1. Read the session log below carefully.
2. Identify: what worked well, what failed, what caused repeated retries, what context was missing.
3. Output ONLY a set of concise CLAUDE.md rules (no preamble, no explanation outside the rules).
4. Format each rule as a bullet point under a "## Learned Rules" section header.
5. Rules must be: actionable, specific, generalisable (not session-specific), and under 2 sentences each.
6. Maximum 10 rules. Skip obvious rules already in standard CLAUDE.md defaults.

Session log:
---
`;

export async function reflectCommand(name: string, opts: ReflectOptions): Promise<void> {
  const cfg = await loadConfig();
  const spinner = ora(`Reflecting on session "${name}"...`).start();

  // Find the log file or handoff file
  const logFile = path.join(CCMUX_DIR, "logs", `${name}.log`);
  const handoffsDir = path.join(CCMUX_DIR, "handoffs");
  let sourceText: string | undefined;
  let sourceLabel = logFile;

  try {
    sourceText = await fs.readFile(logFile, "utf-8");
    sourceLabel = logFile;
  } catch {
    // Fall back to latest handoff file
    try {
      const files = (await fs.readdir(handoffsDir))
        .filter((f) => f.endsWith(`-${name}.md`))
        .sort();
      if (files.length > 0) {
        const latest = path.join(handoffsDir, files[files.length - 1]);
        sourceText = await fs.readFile(latest, "utf-8");
        sourceLabel = latest;
      }
    } catch {
      // ignore
    }
  }

  if (!sourceText) {
    spinner.fail(chalk.red(`No log or handoff found for session "${name}".`));
    console.log(chalk.dim(`  Looked in: ${logFile}`));
    console.log(chalk.dim(`  Looked in: ${handoffsDir}/*-${name}.md`));
    process.exit(1);
  }

  // Truncate very large logs to last 50K chars to fit context
  const MAX_LOG_CHARS = 50_000;
  if (sourceText.length > MAX_LOG_CHARS) {
    sourceText = `...[truncated — showing last ${MAX_LOG_CHARS} chars]...\n` +
      sourceText.slice(-MAX_LOG_CHARS);
  }

  spinner.text = `Analyzing ${path.basename(sourceLabel)}...`;

  const prompt = REFLECTION_PROMPT + sourceText + "\n---\n";

  // Write prompt to temp file to avoid shell injection
  const tmpPromptFile = path.join(CCMUX_DIR, "logs", `.reflect-${name}.tmp`);
  await fs.mkdir(path.dirname(tmpPromptFile), { recursive: true });
  await fs.writeFile(tmpPromptFile, prompt, "utf-8");

  const baseCmd = await resolveClaudeCmd(opts.backend ?? "claude");
  const parsedCmd = parseCmd(baseCmd);
  const claudeBin = parsedCmd[0];
  const claudeExtraArgs = parsedCmd.slice(1);

  const reflection = await runClaudeReflect(
    claudeBin,
    claudeExtraArgs,
    tmpPromptFile,
    opts.backend === "autoclaw" ? cfg.autoclaw.url : undefined
  );

  await fs.unlink(tmpPromptFile).catch(() => {});

  spinner.stop();

  if (!reflection.trim()) {
    console.log(chalk.yellow("  No reflection output received."));
    return;
  }

  console.log(chalk.bold("\nReflection output:"));
  console.log(chalk.dim("─".repeat(60)));
  console.log(reflection);
  console.log(chalk.dim("─".repeat(60)));

  if (opts.outputFile) {
    await fs.writeFile(opts.outputFile, reflection, "utf-8");
    console.log(chalk.green(`\n  Saved to: ${opts.outputFile}`));
    return;
  }

  if (opts.apply) {
    const projectKey = cfg.defaultProject;
    const project = cfg.projects[projectKey];
    if (!project) {
      console.log(chalk.yellow(`  --apply: defaultProject "${projectKey}" not found — cannot auto-apply.`));
      return;
    }
    const claudeMdPath = project.claudeMd ?? path.join(project.path, "CLAUDE.md");
    let existing = "";
    try {
      existing = await fs.readFile(claudeMdPath, "utf-8");
    } catch {
      // CLAUDE.md doesn't exist yet
    }

    // Deduplicate: replace the previous auto-generated block (if any) instead of
    // piling up a fresh one on every `--apply` — matches the documented intent.
    const marker = "\n\n---\n_Auto-generated by `ccmux reflect`_\n\n";
    const block = marker + reflection + "\n";
    const lastIdx = existing.lastIndexOf(marker);
    const next = lastIdx >= 0 ? existing.slice(0, lastIdx) + block : existing + block;
    await fs.writeFile(claudeMdPath, next, "utf-8");
    console.log(chalk.green(`\n  Applied to: ${claudeMdPath}`));
    console.log(chalk.dim("  Review with: git diff HEAD CLAUDE.md"));
  } else {
    console.log(chalk.dim("\n  To apply these rules: ccmux reflect " + name + " --apply"));
    console.log(chalk.dim("  To save to file:      ccmux reflect " + name + " --output-file rules.md"));
  }
}

function parseCmd(cmd: string): string[] {
  // cmd is either "claude" or `ANTHROPIC_BASE_URL="..." claude [--model x]`
  // Strip env var prefix parts (KEY=VALUE), return [binary, ...args]
  const parts = cmd.split(" ");
  const binIdx = parts.findIndex((p) => !p.includes("="));
  return [parts[binIdx] ?? "claude", ...parts.slice(binIdx + 1)];
}

function runClaudeReflect(
  bin: string,
  prefixArgs: string[],
  promptFile: string,
  autoclaUrl?: string
): Promise<string> {
  return new Promise((resolve, reject) => {
    const env: Record<string, string> = { ...(process.env as Record<string, string>) };
    if (autoclaUrl) env["ANTHROPIC_BASE_URL"] = autoclaUrl;

    const args = [...prefixArgs, "--dangerously-skip-permissions", "-p", `@${promptFile}`];
    const child = spawn(bin, args, { env, stdio: ["ignore", "pipe", "pipe"] });

    let out = "";
    let err = "";
    child.stdout?.on("data", (chunk: Buffer) => { out += chunk.toString(); });
    child.stderr?.on("data", (chunk: Buffer) => { err += chunk.toString(); });

    child.on("error", reject);
    child.on("close", (code) => {
      if (code !== 0 && !out.trim()) {
        reject(new Error(`claude exited ${code}: ${err.trim()}`));
      } else {
        resolve(out.trim());
      }
    });
  });
}
